# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/lenovo/Downloads/text-based-rpg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/lenovo/Downloads/text-based-rpg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lenovo/Downloads/text-based-rpg/CMakeFiles /mnt/c/Users/lenovo/Downloads/text-based-rpg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lenovo/Downloads/text-based-rpg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /mnt/c/Users/lenovo/Downloads/text-based-rpg/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named text_rpg

# Build rule for target.
text_rpg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 text_rpg
.PHONY : text_rpg

# fast build rule for target.
text_rpg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/build
.PHONY : text_rpg/fast

src/Character/Character.o: src/Character/Character.cpp.o
.PHONY : src/Character/Character.o

# target to build an object file
src/Character/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Character/Character.cpp.o
.PHONY : src/Character/Character.cpp.o

src/Character/Character.i: src/Character/Character.cpp.i
.PHONY : src/Character/Character.i

# target to preprocess a source file
src/Character/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Character/Character.cpp.i
.PHONY : src/Character/Character.cpp.i

src/Character/Character.s: src/Character/Character.cpp.s
.PHONY : src/Character/Character.s

# target to generate assembly for a file
src/Character/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Character/Character.cpp.s
.PHONY : src/Character/Character.cpp.s

src/Random.o: src/Random.cpp.o
.PHONY : src/Random.o

# target to build an object file
src/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Random.cpp.o
.PHONY : src/Random.cpp.o

src/Random.i: src/Random.cpp.i
.PHONY : src/Random.i

# target to preprocess a source file
src/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Random.cpp.i
.PHONY : src/Random.cpp.i

src/Random.s: src/Random.cpp.s
.PHONY : src/Random.s

# target to generate assembly for a file
src/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Random.cpp.s
.PHONY : src/Random.cpp.s

src/Terminal.o: src/Terminal.cpp.o
.PHONY : src/Terminal.o

# target to build an object file
src/Terminal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Terminal.cpp.o
.PHONY : src/Terminal.cpp.o

src/Terminal.i: src/Terminal.cpp.i
.PHONY : src/Terminal.i

# target to preprocess a source file
src/Terminal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Terminal.cpp.i
.PHONY : src/Terminal.cpp.i

src/Terminal.s: src/Terminal.cpp.s
.PHONY : src/Terminal.s

# target to generate assembly for a file
src/Terminal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/Terminal.cpp.s
.PHONY : src/Terminal.cpp.s

src/character_classes/Archer.o: src/character_classes/Archer.cpp.o
.PHONY : src/character_classes/Archer.o

# target to build an object file
src/character_classes/Archer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Archer.cpp.o
.PHONY : src/character_classes/Archer.cpp.o

src/character_classes/Archer.i: src/character_classes/Archer.cpp.i
.PHONY : src/character_classes/Archer.i

# target to preprocess a source file
src/character_classes/Archer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Archer.cpp.i
.PHONY : src/character_classes/Archer.cpp.i

src/character_classes/Archer.s: src/character_classes/Archer.cpp.s
.PHONY : src/character_classes/Archer.s

# target to generate assembly for a file
src/character_classes/Archer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Archer.cpp.s
.PHONY : src/character_classes/Archer.cpp.s

src/character_classes/Boss.o: src/character_classes/Boss.cpp.o
.PHONY : src/character_classes/Boss.o

# target to build an object file
src/character_classes/Boss.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Boss.cpp.o
.PHONY : src/character_classes/Boss.cpp.o

src/character_classes/Boss.i: src/character_classes/Boss.cpp.i
.PHONY : src/character_classes/Boss.i

# target to preprocess a source file
src/character_classes/Boss.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Boss.cpp.i
.PHONY : src/character_classes/Boss.cpp.i

src/character_classes/Boss.s: src/character_classes/Boss.cpp.s
.PHONY : src/character_classes/Boss.s

# target to generate assembly for a file
src/character_classes/Boss.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Boss.cpp.s
.PHONY : src/character_classes/Boss.cpp.s

src/character_classes/Healer.o: src/character_classes/Healer.cpp.o
.PHONY : src/character_classes/Healer.o

# target to build an object file
src/character_classes/Healer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Healer.cpp.o
.PHONY : src/character_classes/Healer.cpp.o

src/character_classes/Healer.i: src/character_classes/Healer.cpp.i
.PHONY : src/character_classes/Healer.i

# target to preprocess a source file
src/character_classes/Healer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Healer.cpp.i
.PHONY : src/character_classes/Healer.cpp.i

src/character_classes/Healer.s: src/character_classes/Healer.cpp.s
.PHONY : src/character_classes/Healer.s

# target to generate assembly for a file
src/character_classes/Healer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Healer.cpp.s
.PHONY : src/character_classes/Healer.cpp.s

src/character_classes/Mage.o: src/character_classes/Mage.cpp.o
.PHONY : src/character_classes/Mage.o

# target to build an object file
src/character_classes/Mage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Mage.cpp.o
.PHONY : src/character_classes/Mage.cpp.o

src/character_classes/Mage.i: src/character_classes/Mage.cpp.i
.PHONY : src/character_classes/Mage.i

# target to preprocess a source file
src/character_classes/Mage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Mage.cpp.i
.PHONY : src/character_classes/Mage.cpp.i

src/character_classes/Mage.s: src/character_classes/Mage.cpp.s
.PHONY : src/character_classes/Mage.s

# target to generate assembly for a file
src/character_classes/Mage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Mage.cpp.s
.PHONY : src/character_classes/Mage.cpp.s

src/character_classes/Warrior.o: src/character_classes/Warrior.cpp.o
.PHONY : src/character_classes/Warrior.o

# target to build an object file
src/character_classes/Warrior.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Warrior.cpp.o
.PHONY : src/character_classes/Warrior.cpp.o

src/character_classes/Warrior.i: src/character_classes/Warrior.cpp.i
.PHONY : src/character_classes/Warrior.i

# target to preprocess a source file
src/character_classes/Warrior.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Warrior.cpp.i
.PHONY : src/character_classes/Warrior.cpp.i

src/character_classes/Warrior.s: src/character_classes/Warrior.cpp.s
.PHONY : src/character_classes/Warrior.s

# target to generate assembly for a file
src/character_classes/Warrior.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/character_classes/Warrior.cpp.s
.PHONY : src/character_classes/Warrior.cpp.s

src/combat/Action.o: src/combat/Action.cpp.o
.PHONY : src/combat/Action.o

# target to build an object file
src/combat/Action.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/combat/Action.cpp.o
.PHONY : src/combat/Action.cpp.o

src/combat/Action.i: src/combat/Action.cpp.i
.PHONY : src/combat/Action.i

# target to preprocess a source file
src/combat/Action.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/combat/Action.cpp.i
.PHONY : src/combat/Action.cpp.i

src/combat/Action.s: src/combat/Action.cpp.s
.PHONY : src/combat/Action.s

# target to generate assembly for a file
src/combat/Action.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/combat/Action.cpp.s
.PHONY : src/combat/Action.cpp.s

src/combat/Combat.o: src/combat/Combat.cpp.o
.PHONY : src/combat/Combat.o

# target to build an object file
src/combat/Combat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/combat/Combat.cpp.o
.PHONY : src/combat/Combat.cpp.o

src/combat/Combat.i: src/combat/Combat.cpp.i
.PHONY : src/combat/Combat.i

# target to preprocess a source file
src/combat/Combat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/combat/Combat.cpp.i
.PHONY : src/combat/Combat.cpp.i

src/combat/Combat.s: src/combat/Combat.cpp.s
.PHONY : src/combat/Combat.s

# target to generate assembly for a file
src/combat/Combat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/combat/Combat.cpp.s
.PHONY : src/combat/Combat.cpp.s

src/game/Game.o: src/game/Game.cpp.o
.PHONY : src/game/Game.o

# target to build an object file
src/game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/game/Game.cpp.o
.PHONY : src/game/Game.cpp.o

src/game/Game.i: src/game/Game.cpp.i
.PHONY : src/game/Game.i

# target to preprocess a source file
src/game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/game/Game.cpp.i
.PHONY : src/game/Game.cpp.i

src/game/Game.s: src/game/Game.cpp.s
.PHONY : src/game/Game.s

# target to generate assembly for a file
src/game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/game/Game.cpp.s
.PHONY : src/game/Game.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu/MenuManager.o: src/menu/MenuManager.cpp.o
.PHONY : src/menu/MenuManager.o

# target to build an object file
src/menu/MenuManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/menu/MenuManager.cpp.o
.PHONY : src/menu/MenuManager.cpp.o

src/menu/MenuManager.i: src/menu/MenuManager.cpp.i
.PHONY : src/menu/MenuManager.i

# target to preprocess a source file
src/menu/MenuManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/menu/MenuManager.cpp.i
.PHONY : src/menu/MenuManager.cpp.i

src/menu/MenuManager.s: src/menu/MenuManager.cpp.s
.PHONY : src/menu/MenuManager.s

# target to generate assembly for a file
src/menu/MenuManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/menu/MenuManager.cpp.s
.PHONY : src/menu/MenuManager.cpp.s

src/menu/menu.o: src/menu/menu.cpp.o
.PHONY : src/menu/menu.o

# target to build an object file
src/menu/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/menu/menu.cpp.o
.PHONY : src/menu/menu.cpp.o

src/menu/menu.i: src/menu/menu.cpp.i
.PHONY : src/menu/menu.i

# target to preprocess a source file
src/menu/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/menu/menu.cpp.i
.PHONY : src/menu/menu.cpp.i

src/menu/menu.s: src/menu/menu.cpp.s
.PHONY : src/menu/menu.s

# target to generate assembly for a file
src/menu/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/menu/menu.cpp.s
.PHONY : src/menu/menu.cpp.s

src/party/Party.o: src/party/Party.cpp.o
.PHONY : src/party/Party.o

# target to build an object file
src/party/Party.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/party/Party.cpp.o
.PHONY : src/party/Party.cpp.o

src/party/Party.i: src/party/Party.cpp.i
.PHONY : src/party/Party.i

# target to preprocess a source file
src/party/Party.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/party/Party.cpp.i
.PHONY : src/party/Party.cpp.i

src/party/Party.s: src/party/Party.cpp.s
.PHONY : src/party/Party.s

# target to generate assembly for a file
src/party/Party.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/party/Party.cpp.s
.PHONY : src/party/Party.cpp.s

src/skills/Skill.o: src/skills/Skill.cpp.o
.PHONY : src/skills/Skill.o

# target to build an object file
src/skills/Skill.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/skills/Skill.cpp.o
.PHONY : src/skills/Skill.cpp.o

src/skills/Skill.i: src/skills/Skill.cpp.i
.PHONY : src/skills/Skill.i

# target to preprocess a source file
src/skills/Skill.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/skills/Skill.cpp.i
.PHONY : src/skills/Skill.cpp.i

src/skills/Skill.s: src/skills/Skill.cpp.s
.PHONY : src/skills/Skill.s

# target to generate assembly for a file
src/skills/Skill.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/skills/Skill.cpp.s
.PHONY : src/skills/Skill.cpp.s

src/skills/SkillList.o: src/skills/SkillList.cpp.o
.PHONY : src/skills/SkillList.o

# target to build an object file
src/skills/SkillList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/skills/SkillList.cpp.o
.PHONY : src/skills/SkillList.cpp.o

src/skills/SkillList.i: src/skills/SkillList.cpp.i
.PHONY : src/skills/SkillList.i

# target to preprocess a source file
src/skills/SkillList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/skills/SkillList.cpp.i
.PHONY : src/skills/SkillList.cpp.i

src/skills/SkillList.s: src/skills/SkillList.cpp.s
.PHONY : src/skills/SkillList.s

# target to generate assembly for a file
src/skills/SkillList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_rpg.dir/build.make CMakeFiles/text_rpg.dir/src/skills/SkillList.cpp.s
.PHONY : src/skills/SkillList.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... text_rpg"
	@echo "... src/Character/Character.o"
	@echo "... src/Character/Character.i"
	@echo "... src/Character/Character.s"
	@echo "... src/Random.o"
	@echo "... src/Random.i"
	@echo "... src/Random.s"
	@echo "... src/Terminal.o"
	@echo "... src/Terminal.i"
	@echo "... src/Terminal.s"
	@echo "... src/character_classes/Archer.o"
	@echo "... src/character_classes/Archer.i"
	@echo "... src/character_classes/Archer.s"
	@echo "... src/character_classes/Boss.o"
	@echo "... src/character_classes/Boss.i"
	@echo "... src/character_classes/Boss.s"
	@echo "... src/character_classes/Healer.o"
	@echo "... src/character_classes/Healer.i"
	@echo "... src/character_classes/Healer.s"
	@echo "... src/character_classes/Mage.o"
	@echo "... src/character_classes/Mage.i"
	@echo "... src/character_classes/Mage.s"
	@echo "... src/character_classes/Warrior.o"
	@echo "... src/character_classes/Warrior.i"
	@echo "... src/character_classes/Warrior.s"
	@echo "... src/combat/Action.o"
	@echo "... src/combat/Action.i"
	@echo "... src/combat/Action.s"
	@echo "... src/combat/Combat.o"
	@echo "... src/combat/Combat.i"
	@echo "... src/combat/Combat.s"
	@echo "... src/game/Game.o"
	@echo "... src/game/Game.i"
	@echo "... src/game/Game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu/MenuManager.o"
	@echo "... src/menu/MenuManager.i"
	@echo "... src/menu/MenuManager.s"
	@echo "... src/menu/menu.o"
	@echo "... src/menu/menu.i"
	@echo "... src/menu/menu.s"
	@echo "... src/party/Party.o"
	@echo "... src/party/Party.i"
	@echo "... src/party/Party.s"
	@echo "... src/skills/Skill.o"
	@echo "... src/skills/Skill.i"
	@echo "... src/skills/Skill.s"
	@echo "... src/skills/SkillList.o"
	@echo "... src/skills/SkillList.i"
	@echo "... src/skills/SkillList.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /mnt/c/Users/lenovo/Downloads/text-based-rpg/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

